# Generated by Django 3.1.3 on 2020-12-10 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('postion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplpoyee_register.postion')),
            ],
        ),
    ]
